### ISSUE TITLE
Public key generation

### ISSUE THREAD

**Issue by skom-42** [jerson/flutter-openpgp#23]
Hey, guys
How i can generate key for encode method, based on public key that I take from server.

Thank you !

**Comment by jerson** [comment]
Hey, thanks for you question if you are looking for a basic example and if you have a public key only need to call encrypt method

```dart
import 'package:fast_rsa/rsa.dart';

void main() async {
    var result = await OpenPGP.encrypt("text","[publicKey here]");
}

```
and for generate is like this  

```dart
import 'package:openpgp/openpgp.dart';

void main() async {
    var keyOptions = KeyOptions()..rsaBits = 1024;
    var keyPair = await OpenPGP.generate(
            options: Options()
              ..name = 'test'
              ..email = 'test@test.com'
              ..passphrase = passphrase
              ..keyOptions = keyOptions);
}
```
but if you are looking for  "generate key for encode method, based on public key that I take from server" I don't know if it's possible, because the library only allows to generate or use public/private keys (as far i know).

**Comment by skom-42** [comment]
I can do something like this with JS OpenPGP library. 

<img width="749" alt="Снимок экрана 2021-06-15 в 14 33 44" src="https://user-images.githubusercontent.com/43013509/122045678-b3581b00-cde6-11eb-98d6-b4e8a93d0f7b.png">

The main problem is absence of readKey method inFlutter OpenPGP library. As I understand it's something for generation new new key pair, based on public key, that CircleAPI retrived.

**Comment by jerson** [comment]
I think it would be important to know what the getPublicKey method does, because the rest looks like a normal process.


btw the readKey process is done inside the library, it is only necessary to send a string that could be previously generated.
