### ISSUE TITLE
use in native JAVA android

### ISSUE THREAD

**Issue by masooddalman** [jerson/flutter-openpgp#27]
how can I use this library in native JAVA android application?
there are some compiled file inside the android folder.

**Comment by jerson** [comment]
Hi @masooddalman thanks for the questiom, yeah you can use it in android but you will need to go to our main library repo

https://github.com/jerson/openpgp-mobile/releases/tag/v1.2.0

since we use flatbuffers you will need to download for example 

https://github.com/jerson/openpgp-mobile/releases/download/v1.2.0/libopenpgp_bridge_android_v1.2.0.tar.gz

and put all files inside a jniLibs something like https://github.com/jerson/flutter-openpgp/tree/master/android/src/main/jniLibs
then include in your code this
https://github.com/jerson/openpgp-mobile/releases/download/v1.2.0/flatbuffers_libopenpgp_bridge_java_v1.2.0.tar.gz

and use JNI for that 

examples:
https://github.com/jerson/react-native-fast-openpgp/blob/flatbuffers/android/fast-openpgp-adapter.cpp
https://github.com/jerson/react-native-fast-openpgp/blob/flatbuffers/android/src/main/java/com/reactnativefastopenpgp/FastOpenpgpModule.kt



this sound a bit complex, but if you a looking for an old library we used to use an .aar file
https://github.com/jerson/react-native-fast-openpgp/tree/master/android/libs
is just import and then use it

ref: https://github.com/jerson/react-native-fast-openpgp/blob/master/android/src/main/java/dev/jerson/RNFastOpenPGPModule.java
