### ISSUE TITLE
Failed to load dynamic library 'libopenpgp_bridge.so'

### ISSUE THREAD

**Issue by eirtscience** [jerson/flutter-openpgp#39]
I tried the plugin recently and it works flawlessly on Windows. However when I try to build a project which depends on flutter-openpgp on Linux, the location of libopenpgp_bridge.so seems to be incorrect.
In my case I cannot find out libopenpgp_bridge.so in ${PROJECT_NAME}/build/linux/x64/${BUILD_FLAVOR}/bundle/lib/ with both debug and release build, thus getting flutter: Invalid argument(s): Failed to load dynamic library 'libopenpgp_bridge.so': libopenpgp_bridge.so: cannot open shared object file: No such file or directory output on debug console. Then I found that file at ${PROJECT_NAME}/build/linux/x64/${BUILD_FLAVOR}/plugins/openpgp/bundle/lib/ and copy it to the first one, letting openpgp back to work.
Could you please make a fix? So that we don't need to move that file manually every time.
Thanks.

**Comment by jerson** [comment]
Hi @eirtscience thanks for report the issue, im in vacacions now, but I will do when come back home

**Comment by tpouriel** [comment]
Hi !
I'm kind of having the same issue while running unit tests on a linux device but i can't use @eirtscience work around since unit test does not produce a linux executable...
Here is the stack trace producing the error : 

 Invalid argument(s): Failed to load dynamic library 'libopenpgp_bridge.so': libopenpgp_bridge.so: cannot open shared object file: No such file or directory
  dart:ffi                                                    new DynamicLibrary.open
  package:openpgp/bridge/binding.dart 125:33                  Binding.openLib
  package:openpgp/bridge/binding.dart 25:16                   new Binding._internal
  package:openpgp/bridge/binding.dart 16:45                   Binding._singleton
  package:openpgp/bridge/binding.dart                         Binding._singleton
  package:openpgp/bridge/binding.dart 21:12                   new Binding
  package:openpgp/openpgp.dart 164:32                         OpenPGP.bindingEnabled
  package:openpgp/openpgp.dart                                OpenPGP.bindingEnabled
  package:openpgp/openpgp.dart 167:9                          OpenPGP._call
  package:openpgp/openpgp.dart 264:22                         OpenPGP._keyPairResponse
  package:openpgp/openpgp.dart 480:18                         OpenPGP.generate
  package:classifid/src/services/open_pgp_service.dart 23:20  OpenPGPService.generateKeyPair
  test/services/open_pgp_service_test.dart 24:54              main.<fn>
  test/services/open_pgp_service_test.dart 23:63              main.<fn>

Could you consider working on resolving this issue please ?
Thanks

**Comment by jerson** [comment]
Hi @tpouriel cloud you run `flutter doctor` to get more details about you linux distro and version please

**Comment by tpouriel** [comment]
Hi @jerson. This is my configuration.

[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04.1 LTS 4.19.0-21-cloud-amd64, locale en_US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by jerson** [comment]
Hi could you try with latest version https://pub.dev/packages/openpgp/versions/3.5.1

**Comment by jerson** [comment]
cc @eirtscience @tpouriel

**Comment by tpouriel** [comment]
Hi @jerson. It's not working for me... This is my error output now : 

 Invalid argument(s): Failed to load dynamic library '/root/fvm/versions/3.3.10/bin/cache/artifacts/engine/linux-x64/flutter_tester': /root/fvm/versions/3.3.10/bin/cache/artifacts/engine/linux-x64/flutter_tester: cannot dynamically load position-independent executable
  dart:ffi                                                    new DynamicLibrary.open
  package:openpgp/bridge/binding.dart 132:35                  Binding.openLib
  package:openpgp/bridge/binding.dart 26:16                   new Binding._internal
  package:openpgp/bridge/binding.dart 17:45                   Binding._singleton
  package:openpgp/bridge/binding.dart                         Binding._singleton
  package:openpgp/bridge/binding.dart 22:12                   new Binding
  package:openpgp/openpgp.dart 164:32                         OpenPGP.bindingEnabled
  package:openpgp/openpgp.dart                                OpenPGP.bindingEnabled
  package:openpgp/openpgp.dart 167:9                          OpenPGP._call
  package:openpgp/openpgp.dart 264:22                         OpenPGP._keyPairResponse
  package:openpgp/openpgp.dart 480:18                         OpenPGP.generate
  package:classifid/src/services/open_pgp_service.dart 24:20  OpenPGPService.generateKeyPair
  test/src/services/open_pgp_service_test.dart 25:54          main.<fn>


Just to let you know, I updated my Flutter version meanwhile to stay compatible with your plugin dependencies : 
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 4.19.0-21-cloud-amd64, locale en_US)

**Comment by jerson** [comment]
Hi @tpouriel I just tested on my ubuntu and its working fine, also the github action was succesfully executed https://github.com/jerson/flutter-openpgp/actions/runs/3790806984/jobs/6445728036 
also I tested using FVM with 3.3.10  and it worked, not sure that could be the issue for you

btw, is this issue happening also in release mode or only in dev mode ?
```sh
➜  components flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 5.15.0-56-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by jerson** [comment]
Hi @tpouriel @eirtscience we have a PR for this issue, I'm going to be testing and then merge and release a new version, https://github.com/jerson/flutter-openpgp/pull/50

**Comment by jerson** [comment]
New version released https://pub.dev/packages/openpgp/versions/3.5.3 please try with this one, feel free to reopen the issue if its needed

**Comment by tpouriel** [comment]
Hi @jerson !

I just tried to run my unit tests using the version 3.5.3 and it did not go well.
Here is the error output i get now :
```
Invalid argument(s): Failed to load dynamic library 'build/linux/x64/debug/bundle/lib/libopenpgp_bridge.so': build/linux/x64/debug/bundle/lib/libopenpgp_bridge.so: cannot open shared object file: No such file or directory
```

My guess is that it worked on your tests_macos.yml file because you priorly did some integrations tests that made a build phase. And since in my case i'm only doing unit tests, there is no such build folder.

**Comment by jerson** [comment]
Hi @tpouriel please try run flutter run -d linux,  and then run the tests
